# Generated by Django 5.1.4 on 2026-05-05 20:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('elapsed_seconds', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('in_progress', 'Em andamento'), ('completed', 'Concluído'), ('abandoned', 'Abandonado')], default='in_progress', max_length=15)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='workouts.workout')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseSetLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('set_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('load_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_logs', to='workouts.exercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_logs', to='training_sessions.workoutsession')),
            ],
            options={
                'ordering': ['exercise__order', 'set_number'],
            },
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['student'], name='training_se_student_a4c404_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['workout'], name='training_se_workout_bd66d7_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['-started_at'], name='training_se_started_05264b_idx'),
        ),
        migrations.AddIndex(
            model_name='exercisesetlog',
            index=models.Index(fields=['session'], name='training_se_session_a79d80_idx'),
        ),
        migrations.AddIndex(
            model_name='exercisesetlog',
            index=models.Index(fields=['exercise'], name='training_se_exercis_fa5f01_idx'),
        ),
        migrations.AddConstraint(
            model_name='exercisesetlog',
            constraint=models.UniqueConstraint(fields=('session', 'exercise', 'set_number'), name='setlog_unique_per_session_exercise'),
        ),
    ]
