# Generated by Django 5.1.4 on 2026-05-08 17:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniciada em')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalizada em')),
                ('elapsed_seconds', models.IntegerField(default=0, verbose_name='Tempo total (s)')),
                ('status', models.CharField(choices=[('in_progress', 'Em andamento'), ('completed', 'Concluído'), ('abandoned', 'Abandonado')], default='in_progress', max_length=15, verbose_name='Status')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='workouts.workout', verbose_name='Ficha')),
            ],
            options={
                'verbose_name': 'Sessão de treino',
                'verbose_name_plural': 'Sessões de treino',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseSetLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('set_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número da série')),
                ('load_kg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Carga real (kg)')),
                ('reps_done', models.PositiveSmallIntegerField(default=0, help_text='Quantas repetições o aluno conseguiu fazer nesta série.', verbose_name='Repetições feitas')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Concluída')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluída em')),
                ('workout_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_logs', to='workouts.workoutexercise', verbose_name='Exercício na ficha')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_logs', to='training_sessions.workoutsession', verbose_name='Sessão')),
            ],
            options={
                'verbose_name': 'Série executada',
                'verbose_name_plural': 'Séries executadas',
                'ordering': ['workout_exercise__order', 'set_number'],
            },
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['student'], name='training_se_student_a4c404_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['workout'], name='training_se_workout_bd66d7_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['-started_at'], name='training_se_started_05264b_idx'),
        ),
        migrations.AddIndex(
            model_name='exercisesetlog',
            index=models.Index(fields=['session'], name='training_se_session_a79d80_idx'),
        ),
        migrations.AddIndex(
            model_name='exercisesetlog',
            index=models.Index(fields=['workout_exercise'], name='training_se_workout_56f7b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='exercisesetlog',
            constraint=models.UniqueConstraint(fields=('session', 'workout_exercise', 'set_number'), name='setlog_unique_per_session_workoutexercise'),
        ),
    ]
