# Generated by Django 5.1.4 on 2026-05-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Usado para gerar link do WhatsApp. Ex.: +55 11 91234-5678', max_length=20, verbose_name='Telefone (WhatsApp)'),
        ),
        migrations.AddField(
            model_name='user',
            name='uses_internal_payment',
            field=models.BooleanField(db_index=True, default=False, help_text='Se ativo, este usuário usa o sistema de pagamento interno. Pra alunos, só pode ser ativo se o trainer também estiver ativo.', verbose_name='Usa pagamento interno do app?'),
        ),
    ]
