# Generated by Django 5.1.4 on 2026-05-08 17:46

import django.core.validators
import django.db.models.deletion
import uuid
import workouts.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('muscle_group', models.CharField(max_length=80, verbose_name='Grupo muscular')),
                ('default_technique_note', models.TextField(blank=True, help_text='Aparece quando uma ficha não sobrescreve com sua própria dica.', verbose_name='Dica técnica padrão')),
                ('demo_gif', models.FileField(blank=True, help_text='GIF demonstrativo do exercício (até 20 MB).', null=True, upload_to=workouts.validators.exercise_demo_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gif']), workouts.validators.validate_demo_gif_size], verbose_name='GIF demonstrativo')),
                ('is_public', models.BooleanField(db_index=True, default=False, help_text='Se marcado, este exercício aparece pra todos os trainers.', verbose_name='Público?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Exercício (catálogo)',
                'verbose_name_plural': 'Exercícios (catálogo)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('focus', models.CharField(max_length=120, verbose_name='Foco')),
                ('day_label', models.CharField(max_length=40, verbose_name='Dia da semana')),
                ('notes', models.TextField(blank=True, verbose_name='Observações do personal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts_as_student', to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workouts_as_trainer', to=settings.AUTH_USER_MODEL, verbose_name='Personal trainer')),
            ],
            options={
                'verbose_name': 'Ficha de treino',
                'verbose_name_plural': 'Fichas de treino',
                'ordering': ['day_label', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('sets', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Séries')),
                ('reps', models.CharField(help_text='Ex.: "8-12", "12" ou "AMRAP".', max_length=20, verbose_name='Repetições')),
                ('load_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Carga sugerida (kg)')),
                ('rest_seconds', models.PositiveSmallIntegerField(default=60, verbose_name='Descanso (s)')),
                ('technique_note', models.TextField(blank=True, help_text='Sobrescreve a dica padrão do catálogo. Vazio = usa a padrão.', verbose_name='Dica específica desta ficha')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='workouts.exercise', verbose_name='Exercício do catálogo')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='workouts.workout', verbose_name='Ficha')),
            ],
            options={
                'verbose_name': 'Exercício na ficha',
                'verbose_name_plural': 'Exercícios nas fichas',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['muscle_group'], name='workouts_ex_muscle__443f00_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['is_public'], name='workouts_ex_is_publ_70dc8e_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['created_by'], name='workouts_ex_created_5c0b58_idx'),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['student'], name='workouts_wo_student_00987f_idx'),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['trainer'], name='workouts_wo_trainer_b00b4f_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutexercise',
            index=models.Index(fields=['workout'], name='workouts_wo_workout_301e69_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutexercise',
            index=models.Index(fields=['exercise'], name='workouts_wo_exercis_661c99_idx'),
        ),
        migrations.AddConstraint(
            model_name='workoutexercise',
            constraint=models.UniqueConstraint(fields=('workout', 'order'), name='workoutexercise_unique_order_per_workout'),
        ),
    ]
