# Generated by Django 5.1.4 on 2026-05-05 20:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('focus', models.CharField(max_length=120)),
                ('day_label', models.CharField(max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts_as_student', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workouts_as_trainer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day_label', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=120)),
                ('muscle_group', models.CharField(max_length=80)),
                ('sets', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('reps', models.CharField(max_length=20)),
                ('load_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rest_seconds', models.PositiveSmallIntegerField(default=60)),
                ('technique_note', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True, max_length=500)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workout')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['student'], name='workouts_wo_student_00987f_idx'),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['trainer'], name='workouts_wo_trainer_b00b4f_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['workout'], name='workouts_ex_workout_8731a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(fields=('workout', 'order'), name='exercise_unique_order_per_workout'),
        ),
    ]
