# Generated by Django 5.1.4 on 2026-05-05 20:58

import django.core.validators
import workouts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='video_url',
        ),
        migrations.AddField(
            model_name='exercise',
            name='demo_gif',
            field=models.FileField(blank=True, help_text='GIF demonstrativo do exercício (até 20 MB).', null=True, upload_to=workouts.validators.exercise_demo_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gif']), workouts.validators.validate_demo_gif_size]),
        ),
    ]
