# Generated by Django 5.1.4 on 2026-05-09 00:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SetPreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ex.: Hipertrofia 4x10 moderado', max_length=80, verbose_name='Nome')),
                ('sets', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Séries')),
                ('reps', models.CharField(help_text="String livre: '10-12', '8', 'Falha', '15s'.", max_length=30, verbose_name='Repetições')),
                ('load_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Carga sugerida. Vazio quando o preset não fixa carga.', max_digits=6, null=True, verbose_name='Carga (kg)')),
                ('rest_seconds', models.PositiveIntegerField(default=60, verbose_name='Descanso (s)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_presets', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Preset de série',
                'verbose_name_plural': 'Presets de série',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['created_by'], name='workouts_se_created_884221_idx')],
                'constraints': [models.UniqueConstraint(fields=('created_by', 'name'), name='setpreset_unique_name_per_creator')],
            },
        ),
    ]
