# Generated by Django 5.1.4 on 2026-05-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_setpreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='setpreset',
            name='technique_note',
            field=models.TextField(blank=True, help_text='Opcional. Aplicada quando o preset for usado num exercício.', verbose_name='Dica técnica'),
        ),
        migrations.AddField(
            model_name='workout',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Quando True, escondida do aluno e do sync mobile.', verbose_name='Arquivada'),
        ),
    ]
