# Generated by Django 5.1.4 on 2026-05-09 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_setpreset_technique_note_workout_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='setpreset',
            name='set_loads',
            field=models.JSONField(blank=True, default=list, help_text='Ex.: [60, 60, 70, 75]. [] = usa load_kg geral.', verbose_name='Carga por série'),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='set_loads',
            field=models.JSONField(blank=True, default=list, help_text='Ex.: [60, 60, 70, 75] (pirâmide). [] = usa load_kg geral.', verbose_name='Carga por série'),
        ),
        migrations.AlterField(
            model_name='setpreset',
            name='load_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Carga uniforme. Sobrescrita por set_loads se definida.', max_digits=6, null=True, verbose_name='Carga (kg)'),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='load_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Carga uniforme pra todas as séries. Sobrescrita por set_loads se definida.', max_digits=5, null=True, verbose_name='Carga sugerida (kg)'),
        ),
    ]
