# Generated by Django 5.1.4 on 2026-05-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_setpreset_set_loads_workoutexercise_set_loads_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercise',
            name='group_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Mesmo UUID em N itens = superset. NULL = solo.', null=True, verbose_name='ID do grupo conjugado'),
        ),
    ]
