# Generated by Django 5.1.4 on 2026-05-19 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_workoutexercise_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='valid_from',
            field=models.DateField(blank=True, db_index=True, help_text='Antes desta data, a ficha fica oculta pro aluno (permite agendar fichas futuras). Vazio = vale desde já.', null=True, verbose_name='Válida a partir de'),
        ),
        migrations.AddField(
            model_name='workout',
            name='valid_until',
            field=models.DateField(blank=True, db_index=True, help_text='Depois desta data, a ficha fica oculta pro aluno (expirada). Vazio = sem expiração.', null=True, verbose_name='Válida até'),
        ),
    ]
